# @package _group_
data_root_dir: /kaggle/working/lama-main-2000/celeba-hq-dataset
out_root_dir: /kaggle/working/lama-main-2000/experiments/
tb_dir: /kaggle/working/lama-main-2000/tb_logs/
pretrained_models: /kaggle/working/lama-main-2000/
